book:
  author: Shawn W Laffan
  chapters:
  - index.qmd
  - all_publications.qmd
  - 2026.qmd
  - 2025.qmd
  - 2024.qmd
  - 2023.qmd
  - 2022.qmd
  - 2021.qmd
  - 2020.qmd
  - 2019.qmd
  - 2018.qmd
  - 2017.qmd
  - 2016.qmd
  - 2015.qmd
  - 2014.qmd
  - 2013.qmd
  - 2012.qmd
  - 2011_and_earlier.qmd
  - preprint.qmd
  date: '2026-09-10'
  downloads:
  - pdf
  output-file: Biodiverse-publications
  title: Biodiverse publications
editor: source
format:
  html:
    link-external-newwindow: true
    number-sections: false
    theme: zephyr
  pdf:
    number-depth: 2
    number-sections: false
    toc: true
    toc-depth: 3
project:
  output-dir: docs
  type: book
